# .streamlit/secrets.toml

# 决定连接逻辑的开关
USE_CLOUD_REDIS = true

# 必须添加这个键，因为 main.py 正在寻找它
#REDIS_URL = "rediss://default:gQAAAAAAAWFKAAIncDE5YzQ4Zjg3NGVlY2M0M2Q3Yjg4ODZmZTAwYThlNzJkNnAxOTA0NDI@model-mullet-90442.upstash.io:6379"

# 保留备用
UPSTASH_REDIS_URL = "rediss://default:gQAAAAAAAWFKAAIncDE5YzQ4Zjg3NGVlY2M0M2Q3Yjg4ODZmZTAwYThlNzJkNnAxOTA0NDI@model-mullet-90442.upstash.io:6379"
LOCAL_REDIS_URL = "redis://localhost:6379"


GOOGLE_API_KEY = "AIzaSyCbGT8pBKV_GkEJQr4smJ0SdbkBp4eiu8A"
# ==========================================
# J-Studio Redis 数据库环境配置
# ==========================================

# --- 生产环境数据库: BACC-PRO-PROD ---
[BACC_PRO_PROD]
REDIS_URL="rediss://default:gQAAAAAAAWFKAAIncDE5YzQ4Zjg3NGVlY2M0M2Q3Yjg4ODZmZTAwYThlNzJkNnAxOTA0NDI@model-mullet-90442.upstash.io:6379"
# --- 投注数据库: UNIFIED_ACCOUNT_SYSTEM ---
[UNIFIED_ACCOUNT_SYSTEM]
REDIS_URL="rediss://default:gQAAAAAAAVUiAAIncDFmMzVkMzRhZTE4ZTE0MjEzOWQwZWQ0ZTA1NDVlNGFiMXAxODczMzA@smiling-albacore-87330.upstash.io:6379"

